version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: pnpm run dev
    deploy:
      replicas: ${BOT_REPLICAS:-1}
    ports:
      - "${METRICS_PORT:-9090}:9090"
