[package]
name = "nft_mint_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2", features = ["abigen", "ws"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
